CREATE TABLE report_tag_ids
(
    id INTEGER PRIMARY KEY,
    tag TEXT NOT NULL UNIQUE CHECK (tag IN (
        'READ', 'ARCHIVED', 'ATTACKER_NO_LOSS',
        'ATTACKER_SOME_LOSS',
        'ATTACKER_FULL_LOSS',
        'DEFENDER_NO_LOSS',
        'DEFENDER_SOME_LOSS',
        'DEFENDER_FULL_LOSS'
    ))
) STRICT;
