CREATE TABLE unit_ids
(
  id INTEGER PRIMARY KEY,
  unit TEXT NOT NULL UNIQUE CHECK (unit IN ('HERO', 'LEGIONNAIRE', 'PRAETORIAN', 'IMPERIAN', 'EQUITES_IMPERATORIS', 'EQUITES_CAESARIS', 'ROMAN_SCOUT', 'ROMAN_RAM', 'ROMAN_CATAPULT', 'ROMAN_CHIEF', 'ROMAN_SETTLER', 'PHALANX', 'SWORDSMAN', 'THEUTATES_THUNDER', 'DRUIDRIDER', 'HAEDUAN', 'GAUL_SCOUT', 'GAUL_RAM', 'GAUL_CATAPULT', 'GAUL_CHIEF', 'GAUL_SETTLER', 'CLUBSWINGER', 'SPEARMAN', 'AXEMAN', 'PALADIN', 'TEUTONIC_KNIGHT', 'TEUTONIC_SCOUT', 'TEUTONIC_RAM', 'TEUTONIC_CATAPULT', 'TEUTONIC_CHIEF', 'TEUTONIC_SETTLER', 'MERCENARY', 'BOWMAN', 'STEPPE_RIDER', 'MARKSMAN', 'MARAUDER', 'HUN_SCOUT', 'HUN_RAM', 'HUN_CATAPULT', 'HUN_CHIEF', 'HUN_SETTLER', 'SLAVE_MILITIA', 'ASH_WARDEN', 'KHOPESH_WARRIOR', 'ANHUR_GUARD', 'RESHEPH_CHARIOT', 'EGYPTIAN_SCOUT', 'EGYPTIAN_RAM', 'EGYPTIAN_CATAPULT', 'EGYPTIAN_CHIEF', 'EGYPTIAN_SETTLER', 'HOPLITE', 'SHIELDSMAN', 'TWINSTEEL_THERION', 'ELPIDA_RIDER', 'CORINTHIAN_CRUSHER', 'SPARTAN_SCOUT', 'SPARTAN_RAM', 'SPARTAN_CATAPULT', 'SPARTAN_CHIEF', 'SPARTAN_SETTLER', 'PIKEMAN', 'THORNED_WARRIOR', 'GUARDSMAN', 'AXERIDER', 'NATARIAN_KNIGHT', 'NATARIAN_SCOUT', 'NATARIAN_RAM', 'NATARIAN_CATAPULT', 'NATARIAN_CHIEF', 'NATARIAN_SETTLER', 'RAT', 'SPIDER', 'SERPENT', 'BAT', 'WILD_BOAR', 'WOLF', 'BEAR', 'CROCODILE', 'TIGER', 'ELEPHANT'))
) STRICT;

CREATE INDEX idx_unit_ids_unit ON unit_ids(unit);
