name: "Setup: Checkout + Node + Install"
description: "Checkout, setup node and install deps"
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Use Node.js LTS
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        cache: npm
        cache-dependency-path: package-lock.json

    - name: Install modules
      shell: bash
      run: npm ci --prefer-offline --no-audit --no-fund
