/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  readonly '/developer-settings': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path?: never;
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/developer-settings/:developerSettingName': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly developerSettingName: string;
        };
        readonly cookie?: never;
      };
      readonly requestBody: {
        readonly content: {
          readonly 'application/json': unknown;
        };
      };
      readonly responses: never;
    };
    readonly trace?: never;
  };
  readonly '/developer-settings/:heroId/increment-adventure-points': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly heroId: number;
        };
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly trace?: never;
  };
  readonly '/developer-settings/:heroId/spawn-item': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly heroId: number;
        };
        readonly cookie?: never;
      };
      readonly requestBody: {
        readonly content: {
          readonly 'application/json': unknown;
        };
      };
      readonly responses: never;
    };
    readonly trace?: never;
  };
  readonly '/developer-settings/:villageId/resources': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly villageId: number;
        };
        readonly cookie?: never;
      };
      readonly requestBody: {
        readonly content: {
          readonly 'application/json': unknown;
        };
      };
      readonly responses: never;
    };
    readonly trace?: never;
  };
  readonly '/events': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path?: never;
        readonly cookie?: never;
      };
      readonly requestBody: {
        readonly content: {
          readonly 'application/json': unknown;
        };
      };
      readonly responses: never;
    };
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/events/:eventId/cancel': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly eventId: string;
        };
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/map-filters': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path?: never;
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/map-filters/:filterName': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly filterName: string;
        };
        readonly cookie?: never;
      };
      readonly requestBody: {
        readonly content: {
          readonly 'application/json': unknown;
        };
      };
      readonly responses: never;
    };
    readonly trace?: never;
  };
  readonly '/me': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path?: never;
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/me/reputations': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly playerId: number;
        };
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/oasis-bonus-finder': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: {
      readonly parameters: {
        readonly query: {
          readonly x: number;
          readonly y: number;
        };
        readonly header?: never;
        readonly path?: never;
        readonly cookie?: never;
      };
      readonly requestBody: {
        readonly content: {
          readonly 'application/json': unknown;
        };
      };
      readonly responses: never;
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/players/:playerId/hero': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly playerId: number;
        };
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/players/:playerId/hero/adventures': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly playerId: number;
        };
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/players/:playerId/hero/attributes': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly playerId: number;
        };
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly trace?: never;
  };
  readonly '/players/:playerId/hero/equipped-items': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly playerId: number;
        };
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly playerId: number;
        };
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly trace?: never;
  };
  readonly '/players/:playerId/hero/equipped-items/:slot': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post?: never;
    readonly delete: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly playerId: number;
          readonly slot: string;
        };
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/players/:playerId/hero/inventory': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly playerId: number;
        };
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/players/:playerId/hero/item': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly playerId: number;
        };
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/players/:playerId/unit-improvements': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly playerId: number;
        };
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/players/:playerId/villages': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly playerId: number;
        };
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/players/:playerId/villages/:villageId/troops': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly playerId: number;
          readonly villageId: number;
        };
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/players/:playerId/villages/population': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly playerId: number;
        };
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/players/:playerSlug': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly playerSlug: string;
        };
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/preferences': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path?: never;
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/preferences/:preferenceName': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly preferenceName: string;
        };
        readonly cookie?: never;
      };
      readonly requestBody: {
        readonly content: {
          readonly 'application/json': unknown;
        };
      };
      readonly responses: never;
    };
    readonly trace?: never;
  };
  readonly '/quests/collectable-count': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path?: never;
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/server': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path?: never;
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/statistics/overview': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path?: never;
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/statistics/players': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path?: never;
        readonly cookie?: never;
      };
      readonly requestBody: {
        readonly content: {
          readonly 'application/json': unknown;
        };
      };
      readonly responses: never;
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/statistics/villages': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path?: never;
        readonly cookie?: never;
      };
      readonly requestBody: {
        readonly content: {
          readonly 'application/json': unknown;
        };
      };
      readonly responses: never;
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/tiles': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path?: never;
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/tiles/:tileId/bonuses': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly tileId: number;
        };
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/tiles/:tileId/troops': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly tileId: number;
        };
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/tiles/:tileId/world-item': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly tileId: number;
        };
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/villages/:villageId/artifacts': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly villageId: number;
        };
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/villages/:villageId/bookmarks': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly villageId: number;
        };
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/villages/:villageId/bookmarks/:buildingId': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly buildingId: string;
          readonly villageId: number;
        };
        readonly cookie?: never;
      };
      readonly requestBody: {
        readonly content: {
          readonly 'application/json': unknown;
        };
      };
      readonly responses: never;
    };
    readonly trace?: never;
  };
  readonly '/villages/:villageId/building-fields': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly villageId: number;
        };
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly trace?: never;
  };
  readonly '/villages/:villageId/effects': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly villageId: number;
        };
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/villages/:villageId/events': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly villageId: number;
        };
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/villages/:villageId/events/:eventType': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly eventType: string;
          readonly villageId: number;
        };
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/villages/:villageId/oasis/:oasisId': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly oasisId: number;
          readonly villageId: number;
        };
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly delete: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly oasisId: number;
          readonly villageId: number;
        };
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/villages/:villageId/occupiable-oasis': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly villageId: number;
        };
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/villages/:villageId/quests': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly villageId: number;
        };
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/villages/:villageId/quests/:questId/collect': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly questId: string;
          readonly villageId: number;
        };
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/villages/:villageId/rename': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly villageId: number;
        };
        readonly cookie?: never;
      };
      readonly requestBody: {
        readonly content: {
          readonly 'application/json': unknown;
        };
      };
      readonly responses: never;
    };
    readonly trace?: never;
  };
  readonly '/villages/:villageId/researched-units': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly villageId: number;
        };
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/villages/:villageSlug': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: {
      readonly parameters: {
        readonly query?: never;
        readonly header?: never;
        readonly path: {
          readonly villageSlug: string;
        };
        readonly cookie?: never;
      };
      readonly requestBody?: never;
      readonly responses: never;
    };
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
}
