CREATE TABLE villages
(
  id      INTEGER PRIMARY KEY,
  name    TEXT    NOT NULL,
  slug    TEXT UNIQUE,
  tile_id INTEGER NOT NULL REFERENCES tiles (id) ON DELETE CASCADE ON UPDATE CASCADE,
  player_id INTEGER NOT NULL REFERENCES players (id) ON DELETE CASCADE ON UPDATE CASCADE
);

