import { z } from 'zod';
import {
  reportOutcomeSchema,
  reportTagSchema,
  reportTypeSchema,
} from '@pillage-first/types/models/report';
import { tribeSchema } from '@pillage-first/types/models/tribe';

export const getReportsRowSchema = z
  .strictObject({
    id: z.int(),
    player_id: z.int(),
    village_id: z.int(),
    timestamp: z.int(),
    type: reportTypeSchema,
    outcome: reportOutcomeSchema,
    battle_is_raid: z.int().nullable(),
    battle_origin_name: z.string().nullable(),
    battle_origin_x: z.int().nullable(),
    battle_origin_y: z.int().nullable(),
    battle_target_name: z.string().nullable(),
    battle_target_x: z.int().nullable(),
    battle_target_y: z.int().nullable(),
    adventure_id: z.int().nullable(),
    item_id: z.int().nullable(),
    health_before: z.number().nullable(),
    health_after: z.number().nullable(),
    movement_id: z.int().nullable(),
    movement_type: z.enum(['reinforcement', 'relocation']).nullable(),
    movement_tribe: tribeSchema.nullable(),
    movement_origin_tile_id: z.int().nullable(),
    movement_target_tile_id: z.int().nullable(),
    movement_origin_player_name: z.string().nullable(),
    movement_origin_player_slug: z.string().nullable(),
    movement_origin_name: z.string().nullable(),
    movement_origin_x: z.int().nullable(),
    movement_origin_y: z.int().nullable(),
    movement_target_player_name: z.string().nullable(),
    movement_target_player_slug: z.string().nullable(),
    movement_target_name: z.string().nullable(),
    movement_target_x: z.int().nullable(),
    movement_target_y: z.int().nullable(),
    trade_id: z.int().nullable(),
    trade_origin_tile_id: z.int().nullable(),
    trade_target_tile_id: z.int().nullable(),
    trade_origin_name: z.string().nullable(),
    trade_origin_x: z.int().nullable(),
    trade_origin_y: z.int().nullable(),
    trade_target_name: z.string().nullable(),
    trade_target_x: z.int().nullable(),
    trade_target_y: z.int().nullable(),
    trade_wood: z.int().nullable(),
    trade_clay: z.int().nullable(),
    trade_iron: z.int().nullable(),
    trade_wheat: z.int().nullable(),
    tag: reportTagSchema.nullable(),
  })
  .meta({ id: 'GetReportsRow' });
