import type { HeroItem } from 'app/interfaces/models/game/hero';
import { msg } from '@lingui/core/macro';

const artifacts: HeroItem[] = [
  {
    id: 'UNCOMMON_ARTIFACT_MILITARY_TROOP_TRAVEL_SPEED',
    name: msg`Weathered artifact of speed`,
    description: msg``,
    slot: 'non-equipable',
    rarity: 'uncommon',
    category: 'artifact',
    basePrice: null,
    effects: [
      {
        id: 'unitSpeed',
        value: 0.9,
        scope: 'village',
        source: 'artifact',
      },
    ],
  },
  {
    id: 'UNCOMMON_ARTIFACT_MILITARY_TROOP_CARRYING_CAPACITY',
    name: msg`Weathered artifact of carrying`,
    description: msg``,
    slot: 'non-equipable',
    rarity: 'uncommon',
    category: 'artifact',
    basePrice: null,
    effects: [
      {
        id: 'unitCarryCapacity',
        value: 1.1,
        scope: 'village',
        source: 'artifact',
      },
    ],
  },
  {
    id: 'UNCOMMON_ARTIFACT_MILITARY_TROOP_TRAINING_REDUCTION',
    name: msg`Weathered artifact of training`,
    description: msg``,
    slot: 'non-equipable',
    rarity: 'uncommon',
    category: 'artifact',
    basePrice: null,
    effects: [
      {
        id: 'barracksTrainingDuration',
        value: 0.9,
        scope: 'village',
        source: 'artifact',
      },
      {
        id: 'greatBarracksTrainingDuration',
        value: 0.9,
        scope: 'village',
        source: 'artifact',
      },
      {
        id: 'stableTrainingDuration',
        value: 0.9,
        scope: 'village',
        source: 'artifact',
      },
      {
        id: 'greatStableTrainingDuration',
        value: 0.9,
        scope: 'village',
        source: 'artifact',
      },
      {
        id: 'workshopTrainingDuration',
        value: 0.9,
        scope: 'village',
        source: 'artifact',
      },
      {
        id: 'hospitalTrainingDuration',
        value: 0.9,
        scope: 'village',
        source: 'artifact',
      },
    ],
  },
  {
    id: 'UNCOMMON_ARTIFACT_MILITARY_TROOP_WHEAT_CONSUMPTION_REDUCTION',
    name: msg`Weathered artifact of hunger`,
    description: msg``,
    slot: 'non-equipable',
    rarity: 'uncommon',
    category: 'artifact',
    basePrice: null,
    effects: [
      {
        id: 'unitWheatConsumptionReduction',
        value: 0.9,
        scope: 'village',
        source: 'artifact',
      },
    ],
  },
  {
    id: 'UNCOMMON_ARTIFACT_CIVIL_BUILD_TIME_REDUCTION',
    name: msg`Weathered artifact of building`,
    description: msg``,
    slot: 'non-equipable',
    rarity: 'uncommon',
    category: 'artifact',
    basePrice: null,
    effects: [
      {
        id: 'buildingDuration',
        value: 0.9,
        scope: 'village',
        source: 'artifact',
      },
    ],
  },
  {
    id: 'UNCOMMON_ARTIFACT_CIVIL_OASIS_PRODUCTION_BONUS',
    name: msg`Weathered artifact of oasis`,
    description: msg``,
    slot: 'non-equipable',
    rarity: 'uncommon',
    category: 'artifact',
    basePrice: null,
    // TODO: Figure out how to implement this. It should only target oasis bonuses. Or think of another artifact effect
    effects: [
      // {
      //   id: '',
      //   value: 0,
      //   scope: 'global',
      //   source: 'artifact',
      // }
    ],
  },
  {
    id: 'UNCOMMON_ARTIFACT_CIVIL_RESOURCE_PRODUCTION_BONUS',
    name: msg`Weathered artifact of resources`,
    description: msg``,
    slot: 'non-equipable',
    rarity: 'uncommon',
    category: 'artifact',
    basePrice: null,
    effects: [
      {
        id: 'woodProductionBonus',
        value: 1.1,
        scope: 'village',
        source: 'artifact',
      },
      {
        id: 'clayProductionBonus',
        value: 1.1,
        scope: 'village',
        source: 'artifact',
      },
      {
        id: 'ironProductionBonus',
        value: 1.1,
        scope: 'village',
        source: 'artifact',
      },
      {
        id: 'wheatProductionBonus',
        value: 1.1,
        scope: 'village',
        source: 'artifact',
      },
    ],
  },
  // Rare
  {
    id: 'RARE_ARTIFACT_MILITARY_TROOP_TRAVEL_SPEED',
    name: msg`Honed artifact of speed`,
    description: msg``,
    slot: 'non-equipable',
    rarity: 'rare',
    category: 'artifact',
    basePrice: null,
    effects: [
      {
        id: 'unitSpeed',
        value: 0.5,
        scope: 'village',
        source: 'artifact',
      },
    ],
  },
  {
    id: 'RARE_ARTIFACT_MILITARY_TROOP_CARRYING_CAPACITY',
    name: msg`Honed artifact of carrying`,
    description: msg``,
    slot: 'non-equipable',
    rarity: 'rare',
    category: 'artifact',
    basePrice: null,
    effects: [
      {
        id: 'unitCarryCapacity',
        value: 1.5,
        scope: 'village',
        source: 'artifact',
      },
    ],
  },
  {
    id: 'RARE_ARTIFACT_MILITARY_TROOP_TRAINING_REDUCTION',
    name: msg`Honed artifact of training`,
    description: msg``,
    slot: 'non-equipable',
    rarity: 'rare',
    category: 'artifact',
    basePrice: null,
    effects: [
      {
        id: 'barracksTrainingDuration',
        value: 0.5,
        scope: 'village',
        source: 'artifact',
      },
      {
        id: 'greatBarracksTrainingDuration',
        value: 0.5,
        scope: 'village',
        source: 'artifact',
      },
      {
        id: 'stableTrainingDuration',
        value: 0.5,
        scope: 'village',
        source: 'artifact',
      },
      {
        id: 'greatStableTrainingDuration',
        value: 0.5,
        scope: 'village',
        source: 'artifact',
      },
      {
        id: 'workshopTrainingDuration',
        value: 0.5,
        scope: 'village',
        source: 'artifact',
      },
      {
        id: 'hospitalTrainingDuration',
        value: 0.5,
        scope: 'village',
        source: 'artifact',
      },
    ],
  },
  {
    id: 'RARE_ARTIFACT_MILITARY_TROOP_WHEAT_CONSUMPTION_REDUCTION',
    name: msg`Honed artifact of hunger`,
    description: msg``,
    slot: 'non-equipable',
    rarity: 'rare',
    category: 'artifact',
    basePrice: null,
    effects: [
      {
        id: 'unitWheatConsumptionReduction',
        value: 0.5,
        scope: 'village',
        source: 'artifact',
      },
    ],
  },
  {
    id: 'RARE_ARTIFACT_CIVIL_BUILD_TIME_REDUCTION',
    name: msg`Honed artifact of building`,
    description: msg``,
    slot: 'non-equipable',
    rarity: 'rare',
    category: 'artifact',
    basePrice: null,
    effects: [
      {
        id: 'buildingDuration',
        value: 0.5,
        scope: 'village',
        source: 'artifact',
      },
    ],
  },
  {
    id: 'RARE_ARTIFACT_CIVIL_OASIS_PRODUCTION_BONUS',
    name: msg`Honed artifact of oasis`,
    description: msg``,
    slot: 'non-equipable',
    rarity: 'rare',
    category: 'artifact',
    basePrice: null,
    // TODO: Figure out how to implement this. It should only target oasis bonuses. Or think of another artifact effect
    effects: [
      // {
      //   id: '',
      //   value: 0,
      //   scope: 'global',
      //   source: 'artifact',
      // }
    ],
  },
  {
    id: 'RARE_ARTIFACT_CIVIL_RESOURCE_PRODUCTION_BONUS',
    name: msg`Honed artifact of resources`,
    description: msg``,
    slot: 'non-equipable',
    rarity: 'rare',
    category: 'artifact',
    basePrice: null,
    effects: [
      {
        id: 'woodProductionBonus',
        value: 1.5,
        scope: 'village',
        source: 'artifact',
      },
      {
        id: 'clayProductionBonus',
        value: 1.5,
        scope: 'village',
        source: 'artifact',
      },
      {
        id: 'ironProductionBonus',
        value: 1.5,
        scope: 'village',
        source: 'artifact',
      },
      {
        id: 'wheatProductionBonus',
        value: 1.5,
        scope: 'village',
        source: 'artifact',
      },
    ],
  },
  // Epic
  {
    id: 'EPIC_ARTIFACT_MILITARY_TROOP_TRAVEL_SPEED',
    name: msg`Natarian artifact of speed`,
    description: msg``,
    slot: 'non-equipable',
    rarity: 'epic',
    category: 'artifact',
    basePrice: null,
    effects: [
      {
        id: 'unitSpeed',
        value: 0.5,
        scope: 'global',
        source: 'artifact',
      },
    ],
  },
  {
    id: 'EPIC_ARTIFACT_MILITARY_TROOP_CARRYING_CAPACITY',
    name: msg`Natarian artifact of carrying`,
    description: msg``,
    slot: 'non-equipable',
    rarity: 'epic',
    category: 'artifact',
    basePrice: null,
    effects: [
      {
        id: 'unitCarryCapacity',
        value: 1.5,
        scope: 'global',
        source: 'artifact',
      },
    ],
  },
  {
    id: 'EPIC_ARTIFACT_MILITARY_TROOP_TRAINING_REDUCTION',
    name: msg`Natarian artifact of training`,
    description: msg``,
    slot: 'non-equipable',
    rarity: 'epic',
    category: 'artifact',
    basePrice: null,
    effects: [
      {
        id: 'barracksTrainingDuration',
        value: 0.5,
        scope: 'global',
        source: 'artifact',
      },
      {
        id: 'greatBarracksTrainingDuration',
        value: 0.5,
        scope: 'global',
        source: 'artifact',
      },
      {
        id: 'stableTrainingDuration',
        value: 0.5,
        scope: 'global',
        source: 'artifact',
      },
      {
        id: 'greatStableTrainingDuration',
        value: 0.5,
        scope: 'global',
        source: 'artifact',
      },
      {
        id: 'workshopTrainingDuration',
        value: 0.5,
        scope: 'global',
        source: 'artifact',
      },
      {
        id: 'hospitalTrainingDuration',
        value: 0.5,
        scope: 'global',
        source: 'artifact',
      },
    ],
  },
  {
    id: 'EPIC_ARTIFACT_MILITARY_TROOP_WHEAT_CONSUMPTION_REDUCTION',
    name: msg`Natarian artifact of hunger`,
    description: msg``,
    slot: 'non-equipable',
    rarity: 'epic',
    category: 'artifact',
    basePrice: null,
    effects: [
      {
        id: 'unitWheatConsumptionReduction',
        value: 0.5,
        scope: 'global',
        source: 'artifact',
      },
    ],
  },
  {
    id: 'EPIC_ARTIFACT_CIVIL_BUILD_TIME_REDUCTION',
    name: msg`Natarian artifact of building`,
    description: msg``,
    slot: 'non-equipable',
    rarity: 'epic',
    category: 'artifact',
    basePrice: null,
    effects: [
      {
        id: 'buildingDuration',
        value: 0.5,
        scope: 'global',
        source: 'artifact',
      },
    ],
  },
  {
    id: 'EPIC_ARTIFACT_CIVIL_OASIS_PRODUCTION_BONUS',
    name: msg`Natarian artifact of oasis`,
    description: msg``,
    slot: 'non-equipable',
    rarity: 'epic',
    category: 'artifact',
    basePrice: null,
    // TODO: Figure out how to implement this. It should only target oasis bonuses. Or think of another artifact effect
    effects: [
      // {
      //   id: '',
      //   value: 0,
      //   scope: 'global',
      //   source: 'artifact',
      // }
    ],
  },
  {
    id: 'EPIC_ARTIFACT_CIVIL_RESOURCE_PRODUCTION_BONUS',
    name: msg`Natarian artifact of resources`,
    description: msg``,
    slot: 'non-equipable',
    rarity: 'epic',
    category: 'artifact',
    basePrice: null,
    effects: [
      {
        id: 'woodProductionBonus',
        value: 1.5,
        scope: 'global',
        source: 'artifact',
      },
      {
        id: 'clayProductionBonus',
        value: 1.5,
        scope: 'global',
        source: 'artifact',
      },
      {
        id: 'ironProductionBonus',
        value: 1.5,
        scope: 'global',
        source: 'artifact',
      },
      {
        id: 'wheatProductionBonus',
        value: 1.5,
        scope: 'global',
        source: 'artifact',
      },
    ],
  },
  {
    id: 'EPIC_ARTIFACT_CIVIL_ENABLE_GREAT_BUILDINGS',
    name: msg`Natarian artifact of storage`,
    description: msg``,
    slot: 'non-equipable',
    rarity: 'epic',
    category: 'artifact',
    basePrice: null,
    effects: [],
  },
];

export const items: HeroItem[] = [
  ...artifacts,
  {
    id: 'HEALING_POTION',
    name: msg`Healing potion`,
    description: msg``,
    slot: 'consumable',
    rarity: 'common',
    category: 'consumable',
    basePrice: 5,
  },
  {
    id: 'BOOK_OF_WISDOM',
    name: msg`Book of Wisdom`,
    description: msg``,
    slot: 'consumable',
    rarity: 'common',
    category: 'consumable',
    basePrice: 100,
  },
  {
    id: 'ANIMAL_CAGE',
    name: msg`Animal cage`,
    description: msg``,
    slot: 'consumable',
    rarity: 'common',
    category: 'consumable',
    basePrice: 20,
  },
  {
    id: 'REVIVAL_POTION',
    name: msg`Revival potion`,
    description: msg``,
    slot: 'consumable',
    rarity: 'common',
    category: 'consumable',
    basePrice: 20,
  },
  {
    id: 'SILVER',
    name: msg`Silver`,
    description: msg``,
    slot: 'consumable',
    rarity: 'common',
    category: 'currency',
    basePrice: null,
  },
  {
    id: 'WOOD',
    name: msg`Wood`,
    description: msg``,
    slot: 'consumable',
    rarity: 'common',
    category: 'resource',
    basePrice: null,
  },
  {
    id: 'CLAY',
    name: msg`Clay`,
    description: msg``,
    slot: 'consumable',
    rarity: 'common',
    category: 'resource',
    basePrice: null,
  },
  {
    id: 'IRON',
    name: msg`Iron`,
    description: msg``,
    slot: 'consumable',
    rarity: 'common',
    category: 'resource',
    basePrice: null,
  },
  {
    id: 'WHEAT',
    name: msg`Wheat`,
    description: msg``,
    slot: 'consumable',
    rarity: 'common',
    category: 'resource',
    basePrice: null,
  },
];

// Use this for faster lookups
export const itemsMap = new Map<HeroItem['id'], HeroItem>(items.map((item) => [item.id, item]));
