runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js LTS
      uses: actions/setup-node@v6
      with:
        node-version: 'lts/*'
        cache: "npm"
        cache-dependency-path: package-lock.json

    - name: Cache Turbo build setup
      uses: actions/cache@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - name: Install dependencies
      shell: bash
      run: |
        set -euo pipefail
        npm ci --prefer-offline --no-audit --no-fund
