runs:
  using: "composite"
  steps:
    - name: Setup Node.js LTS
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: 'lts/*'
        package-manager-cache: false
        registry-url: https://registry.npmjs.org

    - name: Install dependencies
      shell: bash
      run: |
        set -euo pipefail
        npm ci --no-audit --no-fund --include=optional
